name: Setup SQL Server Main

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    uses: ./.github/workflows/dev-prod-template.yml
    with:
      sql_script: "setup.sql"
      environment_name: "development"
    secrets:
      SQL_SERVER_HOST: ${{ secrets.SQL_SERVER_HOST }}
      SQL_SERVER_PASSWORD: ${{ secrets.SQL_SERVER_PASSWORD }}
      TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}

  deploy-prod:
    needs: deploy-dev
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/dev-prod-template.yml
    with:
      sql_script: "setup.sql"
      environment_name: "production"
    secrets:
      SQL_SERVER_HOST: ${{ secrets.PROD_SQL_SERVER_HOST }}
      SQL_SERVER_PASSWORD: ${{ secrets.PROD_SQL_SERVER_PASSWORD }}
      TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
